import type { Metadata } from "next";
import { Geist_Mono, Montserrat, Cairo } from "next/font/google";
import "../globals.css";
import Header from "@/components/header/Header";
import { NextIntlClientProvider } from "next-intl";
import { getDirection } from "@/i18n/i18n-confige";
import { getMessages } from "next-intl/server";
import MobileBar from "@/components/mobilebar";
import Footer from "@/components/footer";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mern Stack Ecommerce Classy",
  description: "Generated by mohamed salah",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const dir = getDirection(locale);
  const message = await getMessages({ locale });

  return (
    <html
      lang={locale}
      suppressHydrationWarning
      dir={dir === "rtl" ? "rtl" : "ltr"}
    >
      <body
        className={`${
          locale === "ar"
            ? `${cairo.variable}`
            : `${montserrat.variable} ${geistMono.variable}`
        } antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={message}>
          <Header />

          {children}
          <MobileBar />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
